### ISSUE TITLE
Private Cheat

### ISSUE THREAD

**Issue by growstackman123** [csgohacks/master-guide#15]
I think Neverlose.cc belongs to the private cheats section since it has grown to be a highly popular and well performing HvH cheat

**Comment by danielchim** [comment]
Agreed. After I find someone who has experience with neverlsoe I will write it down.

**Comment by growstackman123** [comment]
> Agreed. After I find someone who has experience with neverlsoe I will write it down.

I can help you with this. What's your discord? I'll send you a friend request :)

**Comment by earlviking** [comment]
join the discord server. its in the comments of the pinned post. if u cant find it add me: mcs#2960
