### ISSUE TITLE
foxhook.xyz | descent legit / hvh private cheat

### ISSUE THREAD

**Issue by noxito** [csgohacks/master-guide#26]
foxhook is a Brazilian descent legit cheat, but not-so-good at HvH. This cheat is sell trough a key system in their site (https://foxhook.xyz). It has passed through 3 ban waves. Users report a helpful staff, and quick for just 2 administrators. Also, it have a beautiful menu, which improves a lot the UX. Screenshots:
![Sem título](https://user-images.githubusercontent.com/57924483/94041672-f24dc880-fda0-11ea-84c0-34957c8ea8c7.png)
![Capturar](https://user-images.githubusercontent.com/57924483/94041682-f5e14f80-fda0-11ea-98a6-176e29e433fb.PNG)

**Comment by You02** [comment]
Ok so you mean Moneon with Xy0 Features and a C# loader that would make even Thaisen cry. You best be making better content and or get better at pasting because i can smell ur bullshit from half a mile away

**Comment by noxito** [comment]
> Ok so you mean Moneon with Xy0 Features and a C# loader that would make even Thaisen cry. You best be making better content and or get better at pasting because i can smell ur bullshit from half a mile away

Well, I answered you in the Discord. You already know my answer.

**Comment by danielchim** [comment]
> > Ok so you mean Moneon with Xy0 Features and a C# loader that would make even Thaisen cry. You best be making better content and or get better at pasting because i can smell ur bullshit from half a mile away
> 
> Well, I answered you in the Discord. You already know my answer.

any more media on it?

**Comment by You02** [comment]
> > > Ok so you mean Moneon with Xy0 Features and a C# loader that would make even Thaisen cry. You best be making better content and or get better at pasting because i can smell ur bullshit from half a mile away
> > 
> > 
> > Well, I answered you in the Discord. You already know my answer.
> 
> any more media on it?

Heres some

https://xtremecheats.gg/t/C-Loader-with-ManualMap-bypasses-Trusted-Mode

**Comment by danielchim** [comment]
closed for being a paste

**Comment by danielchim** [comment]
> > Ok so you mean Moneon with Xy0 Features and a C# loader that would make even Thaisen cry. You best be making better content and or get better at pasting because i can smell ur bullshit from half a mile away
> 
> Well, I answered you in the Discord. You already know my answer.

just a FYI please update your https certificate.
![image](https://user-images.githubusercontent.com/12156547/94101093-c3e3f200-fe61-11ea-8cee-f92a9ce57a57.png)

**Comment by You02** [comment]
Also, its been cracked

The dll turned out to be xy0, nothing much was changed whatsoever in the decompiled sudo code
